# Generated by Django 2.0.5 on 2018-05-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_head', models.CharField(max_length=512)),
                ('resp_body', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=256)),
                ('topic_subject', models.CharField(max_length=64)),
                ('topic_logo', models.ImageField(blank=True, default='index.jpeg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='resp_topic',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
        ),
    ]
