# Generated by Django 2.0.5 on 2018-05-23 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='resp_topic',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
        ),
    ]
