# Generated by Django 2.0.5 on 2018-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180523_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='resp_head',
        ),
        migrations.AddField(
            model_name='response',
            name='resp_name',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_logo',
            field=models.ImageField(blank=True, default=' ', upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_subject',
            field=models.CharField(max_length=256),
        ),
    ]
